CREATE TABLE IF NOT EXISTS trade_ai.lstm_hyperparams (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(32),
    window_size INT NOT NULL,
    lstm_neurons INT NOT NULL,
    dropout_rate DOUBLE NOT NULL,
    learning_rate DOUBLE NOT NULL,
    num_epochs INT NOT NULL,
    patience INT NOT NULL,
    min_delta DOUBLE NOT NULL,
    k_folds INT NOT NULL,
    optimizer VARCHAR(32) NOT NULL,
    l1 DOUBLE NOT NULL,
    l2 DOUBLE NOT NULL,
    normalization_scope VARCHAR(32) DEFAULT 'window',
    normalization_method VARCHAR(32) DEFAULT 'auto',
    swing_trade_type VARCHAR(32) DEFAULT 'range',
    num_layers INT NOT NULL,
    bidirectional BOOLEAN DEFAULT FALSE,
    attention BOOLEAN DEFAULT FALSE,
    features TEXT,
    horizon_bars INT NOT NULL,
    threshold_type VARCHAR(32) DEFAULT 'ATR',
    threshold_k DOUBLE DEFAULT 1.0,
    limit_prediction_pct DOUBLE DEFAULT 0.0,
    batch_size INT DEFAULT 256,
    cv_mode VARCHAR(32) DEFAULT 'split',
    use_scalar_v2 BOOLEAN DEFAULT FALSE,
    use_log_return_target BOOLEAN DEFAULT FALSE,
    use_walk_forward_v2 BOOLEAN DEFAULT TRUE,
    walk_forward_splits INT DEFAULT 3,
    embargo_bars INT DEFAULT 0,
    seed BIGINT DEFAULT 42,
    business_profit_factor_cap DOUBLE DEFAULT 3.0,
    business_drawdown_gamma DOUBLE DEFAULT 1.2,
    capital DOUBLE DEFAULT 10000.0,
    risk_pct DOUBLE DEFAULT 0.01,
    sizing_k DOUBLE DEFAULT 1.0,
    fee_pct DOUBLE DEFAULT 0.0005,
    slippage_pct DOUBLE DEFAULT 0.0002,
    kl_drift_threshold DOUBLE DEFAULT 0.15,
    mean_shift_sigma_threshold DOUBLE DEFAULT 2.0,
    use_multi_horizon_avg BOOLEAN DEFAULT FALSE,
    entry_threshold_factor DOUBLE DEFAULT 1.2,
    phase INT,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_lstm_hparams_updated_date (updated_date),
    INDEX idx_lstm_hparams_symbol_updated (symbol, updated_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
