CREATE TABLE trade_ai.lstm_hyperparams (
    symbol VARCHAR(32) PRIMARY KEY,
    window_size INT,
    lstm_neurons INT,
    dropout_rate DOUBLE,
    learning_rate DOUBLE,
    num_epochs INT,
    patience INT,
    min_delta DOUBLE,
    k_folds INT,
    optimizer VARCHAR(16),
    l1 DOUBLE,
    l2 DOUBLE,
    num_layers INT,
    bidirectional BOOLEAN DEFAULT FALSE,
    attention BOOLEAN DEFAULT FALSE,
    normalization_scope VARCHAR(32) DEFAULT 'window',
    normalization_method VARCHAR(32) DEFAULT 'minmax',
    swing_trade_type VARCHAR(32) DEFAULT 'minmax',
    features VARCHAR(255),
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);