CREATE TABLE trade_ai.best_in_out_mix_strategy (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    symbol VARCHAR(32) NOT NULL,
    in_strategy_names TEXT NOT NULL,
    out_strategy_names TEXT NOT NULL,
    in_params TEXT,
    out_params TEXT,
    rendement DOUBLE,
    rendement_check DOUBLE,
    rendement_sum DOUBLE,
    rendement_diff DOUBLE,
    rendement_score DOUBLE,
    trade_count INT,
    win_rate DOUBLE,
    max_drawdown DOUBLE,
    avg_pnl DOUBLE,
    profit_factor DOUBLE,
    avg_trade_bars DOUBLE,
    max_trade_gain DOUBLE,
    max_trade_loss DOUBLE,
    sharpe_ratio DOUBLE,
    stability_score DOUBLE,
    score_swing_trade DOUBLE,
    score_swing_trade_check DOUBLE,
    fltred_out BOOLEAN DEFAULT FALSE,
    check_result TEXT,
    create_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            -- param de test
            initial_capital DOUBLE,
            risk_per_trade DOUBLE,
            stop_loss_pct DOUBLE,
            take_profit_pct DOUBLE,
    nb_simples INT
);
