CREATE TABLE trade_ai.lstm_tuning_metrics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    symbol VARCHAR(32) NOT NULL,
    window_size INT NOT NULL,
    lstm_neurons INT NOT NULL,
    dropout_rate DOUBLE NOT NULL,
    learning_rate DOUBLE NOT NULL,
    l1 DOUBLE NOT NULL,
    l2 DOUBLE NOT NULL,
    num_epochs INT NOT NULL,
    patience INT NOT NULL,
    min_delta DOUBLE NOT NULL,
    optimizer VARCHAR(16) NOT NULL,
    normalization_scope VARCHAR(16) NOT NULL,
    normalization_method VARCHAR(16) NOT NULL,
    swing_trade_type VARCHAR(16) NOT NULL,
    features TEXT NOT NULL,
    mse DOUBLE NOT NULL,
    rmse DOUBLE NOT NULL,
    direction VARCHAR(8) NOT NULL,
    horizon_bars INT NOT NULL,
    profit_total DOUBLE NOT NULL,
    profit_factor DOUBLE NOT NULL,
    win_rate DOUBLE NOT NULL,
    max_drawdown DOUBLE NOT NULL,
    num_trades INT NOT NULL,
    tested_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX(symbol),
    INDEX(tested_date)
);