CREATE TABLE IF NOT EXISTS trade_ai.lstm_tuning_metrics (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  symbol VARCHAR(32) NOT NULL,
  window_size INT NOT NULL,
  lstm_neurons INT NOT NULL,
  dropout_rate DOUBLE NOT NULL,
  learning_rate DOUBLE NOT NULL,
  l1 DOUBLE NOT NULL,
  l2 DOUBLE NOT NULL,
  num_epochs INT NOT NULL,
  patience INT NOT NULL,
  min_delta DOUBLE NOT NULL,
  optimizer VARCHAR(32) NOT NULL,
  normalization_scope VARCHAR(32),
  normalization_method VARCHAR(32),
  swing_trade_type VARCHAR(32),
  features TEXT,
  mse DOUBLE,
  rmse DOUBLE,
  horizon_bars INT,
  profit_total DOUBLE,
  profit_factor DOUBLE,
  win_rate DOUBLE,
  max_drawdown DOUBLE,
  num_trades INT,
  business_score DOUBLE,
  sortino DOUBLE,
  calmar DOUBLE,
  turnover DOUBLE,
  phase_final INT,
  phase_grid INT,
  number_grid INT,
  phase_1_top_n INT,
  holdOut BOOLEAN NOT NULL DEFAULT FALSE,
  avg_bars_in_position DOUBLE,
  use_multi_horizon_avg TINYINT(1) NOT NULL DEFAULT 0,
  entry_threshold_factor DOUBLE,
  tested_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_symbol_date (symbol, tested_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
