CREATE TABLE trade_ai.lstm_hyperparams (
    symbol VARCHAR(32) PRIMARY KEY,
    window_size INT,
    lstm_neurons INT,
    dropout_rate DOUBLE,
    learning_rate DOUBLE,
    num_epochs INT,
    patience INT,
    min_delta DOUBLE,
    k_folds INT,
    optimizer VARCHAR(32),
    l1 DOUBLE,
    l2 DOUBLE,
    num_layers INT, -- correspond à numLstmLayers dans le code (mapping actuel)
    horizon_bars INT,
    bidirectional BOOLEAN DEFAULT FALSE,
    attention BOOLEAN DEFAULT FALSE,
    normalization_scope VARCHAR(32) DEFAULT 'window',
    normalization_method VARCHAR(32) DEFAULT 'auto',
    swing_trade_type VARCHAR(32) DEFAULT 'range',
    features TEXT,
    threshold_type VARCHAR(32) DEFAULT 'ATR',
    threshold_k DOUBLE DEFAULT 1.0,
    limit_prediction_pct DOUBLE DEFAULT 0.0,
    batch_size INT DEFAULT 256,
    cv_mode VARCHAR(32) DEFAULT 'split',
    use_scalar_v2 BOOLEAN DEFAULT FALSE,
    use_log_return_target BOOLEAN DEFAULT FALSE,
    use_walk_forward_v2 BOOLEAN DEFAULT TRUE,
    walk_forward_splits INT DEFAULT 4,
    embargo_bars INT DEFAULT 0,
    seed BIGINT DEFAULT 42,
    business_profit_factor_cap DOUBLE DEFAULT 3.0,
    business_drawdown_gamma DOUBLE DEFAULT 1.2,
    capital DOUBLE DEFAULT 10000.0,
    risk_pct DOUBLE DEFAULT 0.01,
    sizing_k DOUBLE DEFAULT 1.0,
    fee_pct DOUBLE DEFAULT 0.0005,
    slippage_pct DOUBLE DEFAULT 0.0002,
    kl_drift_threshold DOUBLE DEFAULT 0.15,
    mean_shift_sigma_threshold DOUBLE DEFAULT 2.0,
    updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);